name: Tag & Release

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract version from commit message
      id: check-version
      run: |
        version=$(echo '${{ github.event.head_commit.message }}' | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
        if [ -z "$version" ]; then
          echo "Version not found in commit message."
          echo "Sending error to Slack..."
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Error: Version not found in commit message."}' ${{ secrets.SLACK_WEBHOOK_URL }}
          exit 1
        fi
        echo "VERSION=$version" >> $GITHUB_ENV
        echo Extracted version : $version
    - name: Create new release
      if: steps.check-version.outputs.VERSION != ''
      uses: actions/create-release@v1
      env:
        VERSION: ${{ steps.check-version.outputs.VERSION }}
      with: 
        tag_name: v${{ env.VERSION }}
        release_name: v${{ env.VERSION }}
