name: Tag & Release

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Started
      run : |
        echo "Sending to Slack..."
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Build started."}' ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract version from commit message
      id: check-version
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: sh .github/workflows/scripts/extract_version.sh
    - name: Create new release
      if: env.VERSION != ''
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}

